title: Github lac challenge blog
author: Szas
email: szas@marcosalles.com
description: > # this means to ignore newlines until "baseurl:"
  I like games and pets.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
